adm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('adm_dashboard.urls')),
    path('', include('adm_auth.urls')),
]

adm_auth/urls.py
from django.urls import path
from .views import LoginView, LogoutView

urlpatterns = [
    path('', LoginView.as_view(redirect_authenticated_user=True), name="login"),
    path('logout/', LogoutView.as_view(template_name="adm_auth/bootstrap/login.html"),
         name="logout", ),
]

adm_dashboard/urls.py
from django.conf import settings
from django.urls import path
from django.contrib import admin
from .views import (HomeView, )

admin.site.site_header = settings.ADM

app_name = "adm_dashboard"

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
]

adm_auth/models/role.py
from django.contrib.auth.models import Group
from django.db import models
from django.utils.text import slugify
from adm_model import BaseUuidModel


class RoleModelManager(models.Manager):
    def get_by_natural_key(self, name):
        return self.get(name=name)


class Role(BaseUuidModel):

    display_name = models.CharField(
        verbose_name="Display Name",
        max_length=250,
        unique=True,
        db_index=True,
        help_text="(suggest 40 characters max.)",
    )

    name = models.CharField(
        verbose_name="Name",
        max_length=250,
        unique=True,
        db_index=True,
        help_text="This is the stored value, required",
    )

    display_index = models.IntegerField(
        verbose_name="display index",
        default=0,
        db_index=True,
        help_text="Index to control display order if not alphabetical, not required",
    )

    objects = RoleModelManager()

    groups = models.ManyToManyField(Group)

    def __str__(self):
        return self.display_name

    def save(self, *args, **kwargs):
        if not self.name:
            self.name = slugify(self.display_name).lower()
        super().save(*args, **kwargs)

    def natural_key(self):
        return (self.name,)

    class Meta(BaseUuidModel.Meta):
        ordering = ["display_index", "display_name"]

        indexes = [models.Index(fields=["id", "display_name", "display_index"])]

adm_auth/models/signals.py
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.db.models.signals import m2m_changed, post_save
from django.dispatch import receiver

from .user_profile import UserProfile


@receiver(
    post_save, weak=False, sender=User, dispatch_uid="update_user_profile_on_post_save"
)
def update_user_profile_on_post_save(sender, instance, raw, **kwargs):
    if not raw:
        try:
            instance.userprofile
        except ObjectDoesNotExist:
            UserProfile.objects.create(user=instance)


@receiver(
    m2m_changed, weak=False, dispatch_uid="update_user_groups_on_role_m2m_changed"
)
def update_user_groups_on_role_m2m_changed(sender, action, instance, pk_set, **kwargs):

    try:
        assert instance.roles.through == sender
    except (AttributeError, AssertionError):
        pass
    else:
        if action in ["post_add", "post_remove"]:
            if action == "post_add":
                instance.add_groups_for_roles(pk_set)
            elif action == "post_remove":
                instance.remove_groups_for_roles(pk_set)

adm_auth/models/user_profile.py
from django.contrib.auth.models import Group, User
from django.contrib.sites.models import Site
from django.core.validators import RegexValidator
from django.db import models
from django.db.models.deletion import CASCADE
from django.utils.translation import gettext_lazy as _

from .role import Role
from ..constants import CUSTOM_ROLE, STAFF_ROLE


class UserProfile(models.Model):

    user = models.OneToOneField(User, on_delete=CASCADE)

    sites = models.ManyToManyField(Site, blank=True)

    job_title = models.CharField(max_length=100, null=True, blank=True)

    alternate_email = models.EmailField(
        _("Alternate email address"), blank=True, null=True
    )

    mobile = models.CharField(
        max_length=25,
        validators=[RegexValidator(regex="^\+\d+")],
        null=True,
        blank=True,
        help_text="e.g. +0123456789",
    )

    roles = models.ManyToManyField(Role, blank=True)

    def __str__(self):
        return self.user.username

    def add_groups_for_roles(self, pk_set):
        """Add groups to this user for the selected roles.

        Called by m2m signal.
        """
        if CUSTOM_ROLE not in [obj.name for obj in self.roles.all()]:
            group_names = [group.name for group in self.user.groups.all()]
            add_group_names = []
            for role in self.roles.all():
                for group in role.groups.all():
                    if group.name not in group_names:
                        add_group_names.append(group.name)
            add_group_names = list(set(add_group_names))
            for name in add_group_names:
                self.user.groups.add(Group.objects.get(name=name))
                self.user.save()

    def remove_groups_for_roles(self, pk_set):
        """Remove groups from this user for the removed roles.

        Called by m2m signal.
        """
        if CUSTOM_ROLE in [obj.name for obj in Role.objects.filter(pk__in=pk_set)]:
            self.user.groups.clear()
            self.user.userprofile.roles.clear()
            self.user.userprofile.roles.add(Role.objects.get(name=STAFF_ROLE))
        else:
            remove_group_names = []
            current_group_names = []
            for role in self.roles.all():
                current_group_names.extend([group.name for group in role.groups.all()])
            for role in Role.objects.filter(pk__in=pk_set):
                remove_group_names.extend(
                    [
                        group.name
                        for group in role.groups.all()
                        if group.name not in current_group_names
                    ]
                )
            for name in remove_group_names:
                self.user.groups.remove(Group.objects.get(name=name))

adm_model_admin/models.py
from django.db import models

# Create your models here.

adm_auth/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm as BaseForm

from .models import UserProfile


class UserChangeForm(BaseForm):
    def clean(self):
        cleaned_data = super().clean()
        if not self.cleaned_data.get("first_name"):
            raise forms.ValidationError({"first_name": "Required"})
        if not self.cleaned_data.get("last_name"):
            raise forms.ValidationError({"last_name": "Required"})
        if not self.cleaned_data.get("email"):
            raise forms.ValidationError({"email": "Required"})
        return cleaned_data


class UserProfileForm(forms.ModelForm):
    def clean(self):
        cleaned_data = super().clean()

        return cleaned_data

    class Meta:
        model = UserProfile
        fields = "__all__"

adm_auth/views/login_view.py
from django.contrib import messages
from django.contrib.auth.views import LoginView as BaseLoginView


class LoginView(BaseLoginView):
    template_name = f"adm_auth/bootstrap/login.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.request.session.set_test_cookie()
        if not self.request.session.test_cookie_worked():
            messages.add_message(self.request, messages.ERROR, "Please enable cookies.")
        self.request.session.delete_test_cookie()
        return context

adm_auth/views/logout_view.py
from django.contrib.auth.views import LogoutView as BaseLogoutView


class LogoutView(BaseLogoutView):
    next_page = 'login'

adm_dashboard/views/home_view.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = f"adm_dashboard/bootstrap/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context.update(
        # )
        return context

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

adm_model_admin/views.py
from django.shortcuts import render

# Create your views here.

adm_auth/templates/adm_auth/bootstrap/login.html
{% extends 'adm_dashboard/bootstrap/base.html' %}
{% block title %} <title> ADM | Login </title> {% endblock title %}
{% block body-content %}
    <div class="loginBlock" id="login" style="display: block;">
        <div class="alert  alert-block">
            <h1> Welcome to ADM System. Please Sign In </h1>
        </div>
        <div class="dr"><span></span></div>
            <div class="loginForm">
                <form class="form-horizontal" action="" method="post" id="validation">
                    {% csrf_token %}
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span></span>
                            <input type="text" name="username" id="inputUsername" placeholder="Username" class="form-control validate[required]"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
                            <input type="password" name="password" id="inputPassword" placeholder="Password" class="form-control validate[required]"/>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-offset-1 col-md-7">
                            <div class="form-group" style="margin-top: 5px;">
                                <label class="checkbox"><input type="checkbox"> Remember me</label>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <input type="submit" class="btn btn-default btn-block" value="Login in">
                        </div>
                    </div>
                </form>
                <div class="dr"><span></span></div>
                <div class="footer">
                    <div class="row">
                        <div class="col-md-8">
                            <a href="https://www.gnu.org/licenses/gpl-3.0.en.html" class="btn btn-link btn-block">&copy; Licensed for use under GPL 3.0</a>
                        </div>
                        <div class="col-md-4">
                            <a href="" class="btn btn-link btn-block">Version: 1.0.0</a>
                        </div>
                    </div>
                </div>
            </div>
    </div>
{% endblock %}

adm_auth/templates/adm_auth/bootstrap/user_role_description.html
{% if role_names %}
	{% for role_name in role_names %}
		{{ role_name }}<BR>
	{% endfor %}
{% else %}
	<font color="red">Role not defined!<BR></font>
{% endif %}

{% if extra_group_names %}
<font color="orange"><B>Extra groups:</B><BR>
	{% for extra_group_name in extra_group_names %}
		<i>-{{ extra_group_name}}</i><BR>
	{% endfor %}
</font>
{% endif %}

adm_dashboard/templates/adm_dashboard/bootstrap/base.html
{% load edcs_menu %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
    <!--[if gt IE 8]>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <![endif]-->

    {#    Get project name from .env#}
    {% block title %}<title> EDCS </title>{% endblock title %}

    <link rel="icon" type="image/ico" href="{% static 'favicon.ico' %}"/>

    <link href="{% static 'css/stylesheets.css' %}" rel="stylesheet" type="text/css" />


    <script type='text/javascript' src="{% static 'js/plugins/jquery/jquery-1.10.2.min.js' %}"></script>
    <script type='text/javascript' src="{% static 'js/plugins/jquery/jquery-ui-1.10.1.custom.min.js' %}"></script>
    <script type='text/javascript' src="{% static 'js/plugins/jquery/jquery-migrate-1.2.1.min.js' %}"></script>

    <script type='text/javascript' src="{% static 'js/plugins/cookie/jquery.cookies.2.2.0.min.js' %}"></script>

    <script type='text/javascript' src="{% static 'js/plugins/bootstrap.min.js' %}"></script>

    <script type='text/javascript' src="{% static 'js/plugins/sparklines/jquery.sparkline.min.js' %}"></script>


    <script type='text/javascript' src="{% static 'js/plugins/select2/select2.min.js' %}"></script>

    <script type='text/javascript' src="{% static 'js/plugins/uniform/uniform.js' %}"></script>

    <script type='text/javascript' src="{% static 'js/plugins/maskedinput/jquery.maskedinput-1.3.min.js' %}"></script>

    <script type='text/javascript' src="{% static 'js/plugins/validation/languages/jquery.validationEngine-en.js' %}" charset='utf-8'></script>
    <script type='text/javascript' src="{% static 'js/plugins/validation/jquery.validationEngine.js' %}" charset='utf-8'></script>

    <script type='text/javascript' src="{% static 'js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js' %}"></script>
    <script type='text/javascript' src="{% static 'js/plugins/animatedprogressbar/animated_progressbar.js' %}"></script>

    <script type='text/javascript' src="{% static 'js/plugins/qtip/jquery.qtip-1.0.0-rc3.min.js' %}"></script>

    <script type='text/javascript' src="{% static 'js/plugins/cleditor/jquery.cleditor.js' %}"></script>

    <script type='text/javascript' src="{% static 'js/plugins/fancybox/jquery.fancybox.pack.js' %}"></script>

    <script type='text/javascript' src="{% static 'js/plugins/pnotify/jquery.pnotify.min.js' %}"></script>
    <script type='text/javascript' src="{% static 'js/plugins/ibutton/jquery.ibutton.min.js' %}"></script>

    <script type='text/javascript' src="{% static 'js/plugins/scrollup/jquery.scrollUp.min.js' %}"></script>

    <script type='text/javascript' src="{% static 'js/cookies.js' %}"></script>
    <script type='text/javascript' src="{% static 'js/actions.js' %}"></script>
    <script type='text/javascript' src="{% static 'js/plugins.js' %}"></script>
    <script type='text/javascript' src="{% static 'js/settings.js' %}"></script>

</head>
<body>
{% block body-content %}
    <div class="wrapper">
        {% block head %}
            <div class="header">
                <!------------------------------- begin system logo ------------------------------------------->
                <a class="logo" href="{% url 'adm_dashboard:home' %}">
{#                    <img src="{% static 'img/logo.png' %}" alt="edcs-logo" title="edcs"/>#}
                    <p>
                        <span style="font-weight: bold;color: #ffffff; font-size: x-large">
                            ADM </span> &nbsp;&nbsp;
                    </p>
                </a>
                <!------------------------------- end system logo ------------------------------------------->
                <!------------------------------- start template theme settings ------------------------------------------->

                <!------------------------------- end template theme settings ------------------------------------------->
            </div>
        {% endblock head %}
        {% block menu %}
            <div class="menu">
                <!---------------------------- Begin of top menu section for user info ---------------------------------------->
                {% block user-info-menu %}
                    <div class="breadLine">
                        <div class="arrow"></div>
                        <div class="adminControl active">
                            Hi, {{ user.first_name }}
                        </div>
                    </div>
                    <div class="admin">
                        <div class="image">
                            <img src="{% static 'img/users/blank.png' %}" class="img-thumbnail"/>
                        </div>
                        <ul class="control">
                            <li><span class="glyphicon glyphicon-comment"></span> <a href="#">Messages</a> <a href="#" class="caption red">0</a></li>
                            <li><span class="glyphicon glyphicon-cog"></span> <a
                                    href="/admin">Administration</a></li>
                            <li><span class="glyphicon glyphicon-share-alt"></span> <a href="{% url 'logout' %}">Logout</a></li>
                        </ul>
                        <div class="info">
                            <span>Welcome back! Your last visit: {{ user.last_login }}</span>
                        </div>
                    </div>
                {% endblock user-info-menu %}
                <!------------------------- End of top menu section for user info ------------------------------------------------>
                {% block main-menu %}
                    {% main_menu %}
                {% endblock main-menu %}
                {% block bottom-summary %}
                    <!------------------------------------- bottom summary ------------------------------>
                    {% bottom_summary %}
                    <!-------------------------------- end bottom summary ------------------------->
                {% endblock bottom-summary %}
            </div>
        {% endblock menu %}
        {% block content %}
            <div class="content">
                {% block top-content-menu %}
                    <!--------------------------------- start top page navigation-menu ----------------------------------->
                    <div class="breadLine">
                        <!--------------------------------- start left items top page navigation-menu ----------------------------------->
                        <ul class="breadcrumb">
                            <li><a href="#">Adm</a> <span class="divider">></span></li>
                            <li class="active">Dashboard</li>
                        </ul>
                        <!--------------------------------- end left items top page navigation-menu ----------------------------------->

                        <!--------------------------------- start right items top page navigation-menu ----------------------------------->

{#                        {% EdcsInfo %}#}
                        <!--------------------------------- end right items top page navigation-menu ----------------------------------->
                    </div>
                    <!--------------------------------- end top page navigation-menu ----------------------------------->
                {% endblock top-content-menu %}

                {% block main-content %}

                {% endblock main-content %}
            </div>
        {% endblock content %}
    </div>
{% endblock body-content %}

</body>

</html>

adm_dashboard/templates/adm_dashboard/bootstrap/buttons/add_consent_button.html
{% if not consented and eligible %}
    <a href="{{ subject_consent_add_url }}" class="btn btn-sm btn-warning tip" title="{{ title }}">
    Consent <span class="glyphicon glyphicon-file glyphicon glyphicon-white"></span>
</a>
{% endif %}

adm_dashboard/templates/adm_dashboard/bootstrap/buttons/add_edit_crf_button.html
<a href="{{ href }}" class="btn btn-sm {{ btn }} tip" title="{{ title }}">
    <span class="glyphicon {{ icon }} glyphicon glyphicon-white"></span> {{ text }}
</a>

adm_dashboard/templates/adm_dashboard/bootstrap/buttons/appointment_button.html
<a href="#" class="btn btn-sm btn-default tip" title="Edit Appointment" {{ disabled }}>
    <span class="glyphicon glyphicon-pencil glyphicon glyphicon-white"></span> Appt
</a>

adm_dashboard/templates/adm_dashboard/bootstrap/buttons/dashboard_button.html
{% if consented %}
    <a href="{{ subject_dashboard_url }}" class="btn btn-sm btn-info tip" title="{{ title }}">
    Dashboard <span class="glyphicon glyphicon-share-alt glyphicon glyphicon-white"></span>
</a>
{% endif %}

adm_dashboard/templates/adm_dashboard/bootstrap/buttons/done_button.html
{% if appt_status == 'done' %}
    <a href="#" class="btn btn-sm btn-default tip" title="Visit Done">
        Done
    </a>
{% endif %}

adm_dashboard/templates/adm_dashboard/bootstrap/buttons/eligibility_button.html
{% if not eligible %}
    <button href="#" class="btn btn-sm btn-danger tip" title="{{ comment }}" disabled>
        {{ display_label }} <span class="glyphicon glyphicon-alert glyphicon glyphicon-white"></span>
    </button>
{% endif %}

adm_dashboard/templates/adm_dashboard/bootstrap/buttons/forms_button.html
{% if appt_status %}
    <a href="{{ href }}" class="btn btn-sm btn-info tip" title="{{ title }}">
        Forms <span class="glyphicon glyphicon-share-alt glyphicon glyphicon-white"></span>
    </a>
{% endif %}

adm_dashboard/templates/adm_dashboard/bootstrap/buttons/incomplete_button.html
<a href="#" class="btn btn-sm btn-default tip" title="">
    <span class="glyphicon glyphicon-pencil glyphicon glyphicon-white"></span> Incomplete
</a>

adm_dashboard/templates/adm_dashboard/bootstrap/buttons/screening_button.html
<a href="{{ href }}" class="btn btn-sm btn-default tip" title="{{ title }}">
    <span class="glyphicon glyphicon-pencil glyphicon glyphicon-white"></span>
</a>

adm_dashboard/templates/adm_dashboard/bootstrap/buttons/start_button.html
{% if appt_status == 'start' %}
    <a href="{{ href }}" class="btn btn-sm btn-warning tip" title="Start Visit">
        Start <span class="glyphicon glyphicon-plus glyphicon glyphicon-white"></span>
    </a>
{% endif %}

adm_dashboard/templates/adm_dashboard/bootstrap/buttons/start_visit_button.html
{% if status == "new" %}
    <a href="{{ href }}" class="btn btn-sm btn-default tip" title="{{ title }}">
        Start Visit
    </a>
{% endif %}

adm_dashboard/templates/adm_dashboard/bootstrap/buttons/unschedule_button.html
<a href="#" class="btn btn-sm btn-default tip" title="Unscheduled Appointment">
    <span class="glyphicon glyphicon-user glyphicon glyphicon-white"></span>
</a>

adm_dashboard/templates/adm_dashboard/bootstrap/buttons/visit_report_button.html
<a href="#" class="btn btn-sm btn-default tip" title="Visit Report">
    Visit Report
</a>

adm_dashboard/templates/adm_dashboard/bootstrap/home.html
{% extends 'adm_dashboard/bootstrap/base.html' %}
{% load edcs_menu %}
{% block title %}<title> EDCS | Dashboard </title>{% endblock title %}
{% block main-content %}
    <div class="workplace">
        <!-------------------------------------------- start top button icons ------------------------------------------>
        {% top_button_icon %}
        <!-------------------------------------------- end top button icons ------------------------------------------>
        <!--------------------------------------- start count widget -------------------------------------------->
        {% summary_menu %}
        <!--------------------------------------- end count widget -------------------------------------------->
        <div class="dr"><span></span></div>
        <div class="row">
            <!-------------------- start news & update widget --------------------->

            <!-------------------- end news & updates widget --------------------->

            <!-------------------- start today appointment widget --------------------->

            <!-------------------- end today appointment widget --------------------->
        </div>
        <div class="dr"><span></span></div>
    </div>
{% endblock main-content %}

adm_dashboard/templates/adm_dashboard/bootstrap/info.html
<ul class="buttons">
    <li>
        <a href="#" class="link_bcPopupList"><span class="glyphicon glyphicon-info-sign"></span><span class="text"><strong>System Info</strong></span></a>
        <div id="bcPopupList" class="popup">
            <div class="head clearfix">
                <div class="arrow"></div>
                <span class="isw-settings"></span>
                <span class="name">About EDCS</span>
            </div>
            <div class="body-fluid users">
                <div class="item clearfix">
                    <div class="info">
                        <a href="#" class="name">Project Name : </a>
                        <span>{{ project_name }}</span>
                    </div>
                </div>
                <div class="item clearfix">
                    <div class="info">
                        <a href="#" class="name">Institution : </a>
                        <span>{{ institution }}</span>
                    </div>
                </div>
                <div class="item clearfix">
                    <div class="info">
                        <a href="#" class="name">Copyright &copy : </a>
                        <span>{{ copyright }}</span>
                    </div>
                </div>
                <div class="item clearfix">
                    <div class="info">
                        <a href="#" class="name">License : </a>
                        <span>{{ license }}</span>
                    </div>
                </div>
                <div class="item clearfix">
                    <div class="info">
                        <a href="#" class="name">Version : </a>
                        <span>{{ revision }}</span>
                    </div>
                </div>
                <div class="item clearfix">
                    <div class="info">
                        <a href="#" class="name">Disclaimer : </a>
                        <span>{{ disclaimer }}</span>
                    </div>
                </div>
            </div>
            <div class="footer">
                <button class="btn btn-default link_bcPopupList" type="button">Close</button>
            </div>
        </div>
    </li>
    <li>
        <a href="#" class="link_bcPopupSearch"><span class="glyphicon glyphicon-search"></span><span class="text">Search</span></a>
        <div id="bcPopupSearch" class="popup">
            <div class="head clearfix">
                <div class="arrow"></div>
                <span class="isw-zoom"></span>
                <span class="name">Search</span>
            </div>
            <div class="body search">
                <input type="text" placeholder="Some text for search..." name="search"/>
            </div>
            <div class="footer">
                <button class="btn btn-default" type="button">Search</button>
                <button class="btn btn-danger link_bcPopupSearch" type="button">Close</button>
            </div>
        </div>
    </li>
</ul>

adm_dashboard/templates/adm_dashboard/bootstrap/labels/login_uat_label.html
{% if uat %}
<p style="margin-top: 4%"><strong>Note: This site is for testing purpose only.</strong></p>
{% endif %}

adm_dashboard/templates/adm_dashboard/bootstrap/menu/bottom-summary.html
<div class="widget-fluid">
    <div class="wBlock clearfix">
        <div class="dSpace">
            <h3>Requested</h3>
            <span class="number"> 0 </span>
        </div>
        <div class="dSpace">
            <h3>Checked</h3>
            <span class="number"> 0 </span>
        </div>
    </div>
</div>

adm_dashboard/templates/adm_dashboard/bootstrap/menu/consent-panel.html
<div class="pull-right col-md-4">
    <div class="head clearfix">
        <div class="isw-documents"></div>
        <h1>CONSENTS</h1>
    </div>
    <div class="block-fluid accordion">
        <h3></h3>
        <div>
            <div class="row">
                <div class="container-fluid">
                    <div class="col-md-12 clearfix" >
                        <div class="block-fluid sNavigation">
                            <ul>
                                <li>
                                    <a href="{{ href }}" style="color: #2e6da4;font-weight: bolder">
                                        <span class="glyphicon glyphicon-thumbs-up glyphicon glyphicon-blue"></span>
                                        Consented {{ consent_date|date:"d M Y H:i:s"  }}
                                    </a>
                                    <span class="arrow"></span>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

adm_dashboard/templates/adm_dashboard/bootstrap/menu/main-menu.html
<ul class="navigation">
    <li class="active">
        <a href="{% url 'adm_dashboard:home' %}">
            <span class="isw-grid"></span><span class="text">Dashboard</span>
        </a>
    </li>
    <li>
        <a href="">
            <span class="isw-empty_document"></span><span class="text">Add Request</span>
        </a>
    </li>
    <li>
        <a href="">
            <span class="isw-sync"></span><span class="text">Request List</span>
        </a>
    </li>
</ul>

<div class="dr"><span></span></div>
<div class="widget-fluid"><div id="menuDatepicker"></div></div>
 <div class="dr"><span></span></div>
<div class="widget">
    <div class="input-group">
        <input id="appendedInputButton" class="form-control" type="text">
        <div class="input-group-btn">
            <button class="btn btn-default" type="button">Search</button>
        </div>
    </div>
</div>
<div class="dr"><span></span></div>

adm_dashboard/templates/adm_dashboard/bootstrap/menu/news-update.html
<div class="col-md-4">
    <div class="head clearfix">
        <div class="isw-edit"></div>
        <h1> News and Updates </h1>
{#        <ul class="buttons">#}
{#            <li>#}
{#                <a href="#" class="isw-text_document"></a>#}
{#            </li>#}
{#            <li>#}
{#                <a href="#" class="isw-settings"></a>#}
{#                <ul class="dd-list">#}
{#                    <li><a href="#"><span class="isw-list"></span> Show all</a></li>#}
{#                    <li><a href="#"><span class="isw-edit"></span> Add new</a></li>#}
{#                    <li><a href="#"><span class="isw-refresh"></span> Refresh</a></li>#}
{#                </ul>#}
{#            </li>#}
{#        </ul>#}
    </div>
{#    <div class="block news scrollBox">#}
{#        <div class="scroll" style="height: 270px;">#}
{#            <div class="item">#}
{#                <a href="#">Running System Live demo.</a>#}
{#                <p>Phasellus ut diam quis dolor mollis tristique. Suspendisse vestibulum convallis felis vitae facilisis. Praesent eu nisi vestibulum erat lacinia sollicitudin. Cras nec risus dolor, ut tristique neque. Donec mauris sapien, pellentesque at porta id, varius eu tellus.</p>#}
{#                <span class="date">02.11.2012 14:23</span>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
</div>

adm_dashboard/templates/adm_dashboard/bootstrap/menu/summary-menu.html
<div class="row">
    <div class="col-md-4">
        <div class="wBlock blue clearfix">
            <div class="dSpace">
                <h3>Requested</h3>
                <span class="number">0</span>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="wBlock green clearfix">
            <div class="dSpace">
                <h3>Checked</h3>
                <span class="number">0</span>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="wBlock red clearfix">
            <div class="dSpace">
                <h3> Pending </h3>
                <span class="number">0</span>
            </div>
        </div>
    </div>
</div>